#!/usr/bin/env python3
"""
Clean up old test data and organize new results
Removes legacy test files and creates clean test_results structure
"""

import os
import shutil
from pathlib import Path
from datetime import datetime

def cleanup_old_data():
    """Remove old test files and legacy data"""
    
    base_dir = Path(".")
    
    # Files to delete (old test files)
    old_test_files = [
        "test_encode_v2.py",
        "test_comprehensive.py",
        "test_roundtrip.py",
        "test_simplified.py",
        "test_trad.py",
        "test_ja_kanji.py",
        "debug_kakasi.py",
        "test_segments.py"
    ]
    
    # Backup log first
    backup_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    print("🧹 Cleaning up old test files...")
    print("=" * 60)
    
    for filename in old_test_files:
        filepath = base_dir / filename
        if filepath.exists():
            # Move to archive instead of delete
            archive_dir = base_dir / "results" / "archived_tests"
            archive_dir.mkdir(parents=True, exist_ok=True)
            
            archived_path = archive_dir / f"{filename}.{backup_timestamp}.bak"
            try:
                shutil.move(str(filepath), str(archived_path))
                print(f"✅ Archived: {filename} → {archived_path.relative_to(base_dir)}")
            except Exception as e:
                print(f"⚠️  Failed to archive {filename}: {e}")

    # Directories to archive (old outputs)
    dirs_to_archive = [
        base_dir / "logs" / "old_run"  # If exists
    ]
    
    # Create clean structure
    clean_dirs = [
        "results/test_results",
        "results/test_outputs",
        "results/archived_tests",
        "results/docs"
    ]
    
    print("\n📁 Creating clean directory structure...")
    for dirname in clean_dirs:
        dirpath = base_dir / dirname
        dirpath.mkdir(parents=True, exist_ok=True)
        print(f"✅ Created: {dirname}")

    print("\n" + "=" * 60)
    print("✨ Cleanup complete!")
    print(f"📝 Timestamp: {backup_timestamp}")
    print("\n📊 Ready for new test results:")
    print("  • results/test_results/      ← Test metrics (JSON, logs)")
    print("  • results/test_outputs/      ← Test examples and outputs")
    print("  • results/archived_tests/    ← Old test files (backup)")


def create_index():
    """Create index file for results"""
    
    index_content = """# Test Results Index

## Structure

```
results/
├── test_results/
│   ├── test_results.json        # Machine-readable results
│   ├── test_report.md           # Markdown report
│   └── execution_log.txt        # Execution logs
├── test_outputs/
│   ├── translation_examples.txt
│   ├── mixed_language_tests.txt
│   └── edge_case_results.txt
├── archived_tests/              # Old test files (backup)
└── docs/                        # Documentation
    └── testing_methodology.md
```

## How to Generate Reports

1. Run main test harness:
   ```bash
   python3 test_harness.py
   ```

2. View results:
   ```bash
   cat results/test_results/test_report.md
   cat results/test_results/test_results.json
   ```

3. Compare benchmarks:
   ```bash
   python3 benchmark_compare.py
   ```

## Files Generated

- `test_results.json` - Complete test metrics (time, error rate, output samples)
- `test_report.md` - Human-readable report with tables and examples
- `execution_log.txt` - Timestamp logs of each test execution
- `benchmark_comparison.csv` - v5.3.1 vs baseline comparison

## Last Updated

Generated by `test_harness.py` - structured scientific testing framework
"""
    
    index_path = Path("results") / "INDEX.md"
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(index_content)
    
    print(f"✅ Created results index: {index_path}")


if __name__ == "__main__":
    cleanup_old_data()
    create_index()
